<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0.1 (Python 3.6.13 on darwin)" generated="20210428 19:04:16.969" rpa="false" schemaversion="2">
<suite id="s1" name="DefineFunction" source="/Users/yuetao/PythonProject/RF_Test/MyWork/DefineFunction.robot">
<test id="s1-t1" name="test 01">
<kw name="Evaluate" library="BuiltIn">
<var>${a}</var>
<arg>int(4)</arg>
<doc>Evaluates the given expression in Python and returns the result.</doc>
<msg timestamp="20210428 19:04:17.003" level="INFO">${a} = 4</msg>
<status status="PASS" starttime="20210428 19:04:17.002" endtime="20210428 19:04:17.003"/>
</kw>
<kw name="Evaluate" library="BuiltIn">
<var>${b}</var>
<arg>int(5)</arg>
<doc>Evaluates the given expression in Python and returns the result.</doc>
<msg timestamp="20210428 19:04:17.003" level="INFO">${b} = 5</msg>
<status status="PASS" starttime="20210428 19:04:17.003" endtime="20210428 19:04:17.003"/>
</kw>
<kw name="subtraction">
<var>${add}</var>
<arg>${a}</arg>
<arg>${b}</arg>
<msg timestamp="20210428 19:04:17.005" level="FAIL">No keyword with name 'subtraction' found.</msg>
<status status="FAIL" starttime="20210428 19:04:17.005" endtime="20210428 19:04:17.005"/>
</kw>
<kw name="Log" library="BuiltIn">
<arg>${add}</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" starttime="20210428 19:04:17.005" endtime="20210428 19:04:17.005"/>
</kw>
<doc>测试自定义包</doc>
<status status="FAIL" starttime="20210428 19:04:17.002" endtime="20210428 19:04:17.005">No keyword with name 'subtraction' found.</status>
</test>
<status status="FAIL" starttime="20210428 19:04:16.970" endtime="20210428 19:04:17.006"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="DefineFunction">DefineFunction</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210428 19:04:17.001" level="ERROR">Error in file '/Users/yuetao/PythonProject/RF_Test/MyWork/DefineFunction.robot' on line 3: Importing library 'MyLibrary' failed: ModuleNotFoundError: No module named 'my_operation'
Traceback (most recent call last):
  File "/opt/anaconda3/envs/python36/lib/python3.6/site-packages/MyLibrary/__init__.py", line 8, in &lt;module&gt;
    from my_operation import MyOperation
PYTHONPATH:
  /opt/anaconda3/envs/python36/bin
  /opt/anaconda3/envs/python36/lib/python36.zip
  /opt/anaconda3/envs/python36/lib/python3.6
  /opt/anaconda3/envs/python36/lib/python3.6/lib-dynload
  /opt/anaconda3/envs/python36/lib/python3.6/site-packages</msg>
</errors>
</robot>
